-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 16:28:20 2019
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DonPreguntonBBDD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DonPreguntonBBDD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DonPreguntonBBDD` ;
USE `DonPreguntonBBDD` ;

-- -----------------------------------------------------
-- Table `DonPreguntonBBDD`.`Asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonPreguntonBBDD`.`Asignatura` (
  `idAsignatura` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Clase_idClase` VARCHAR(20) NULL,
  PRIMARY KEY (`idAsignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DonPreguntonBBDD`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonPreguntonBBDD`.`Profesor` (
  `idProfesor` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellido` VARCHAR(20) NOT NULL,
  `DNI` VARCHAR(20) NOT NULL,
  `Inicio_Jornadas` VARCHAR(20) NOT NULL,
  `Final_Jornada` VARCHAR(20) NULL,
  `NumSS` VARCHAR(30) NOT NULL,
  `Sueldo` INT NOT NULL,
  `Pr_Contrasenia` VARCHAR(45) NOT NULL,
  `Num_cuenta` VARCHAR(45) NOT NULL,
  `Clase_idClase` VARCHAR(20) NULL,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DonPreguntonBBDD`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonPreguntonBBDD`.`Pago` (
  `idPago` VARCHAR(20) NOT NULL,
  `idProfesores` VARCHAR(20) NOT NULL,
  `idClase` VARCHAR(20) NULL,
  `idAlumno` VARCHAR(20) NOT NULL,
  `cantidad` INT NOT NULL,
  `cantToProf` INT NOT NULL,
  PRIMARY KEY (`idPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DonPreguntonBBDD`.`Clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonPreguntonBBDD`.`Clase` (
  `idClase` VARCHAR(20) NOT NULL,
  `idProfesor` VARCHAR(20) NOT NULL,
  `idAlumno` VARCHAR(20) NOT NULL,
  `idAsignatura` VARCHAR(20) NOT NULL,
  `idHorario` VARCHAR(20) NOT NULL,
  `Pago_idPago` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idClase`, `Pago_idPago`),
  INDEX `fk_Clase_Pagos1_idx` (`Pago_idPago` ASC),
  CONSTRAINT `fk_Clase_Pagos1`
    FOREIGN KEY (`Pago_idPago`)
    REFERENCES `DonPreguntonBBDD`.`Pago` (`idPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DonPreguntonBBDD`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonPreguntonBBDD`.`Alumno` (
  `idAlumno` VARCHAR(20) NOT NULL,
  `Nombre` VARCHAR(20) NOT NULL,
  `Apellido` VARCHAR(20) NOT NULL,
  `DNI` VARCHAR(20) NOT NULL,
  `tarjeta_bancaria` INT NOT NULL,
  `Clase_idClase` VARCHAR(20) NULL,
  `Al_Contrasenia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlumno`),
  INDEX `fk_Alumno_Clase1_idx` (`Clase_idClase` ASC),
  CONSTRAINT `fk_Alumno_Clase1`
    FOREIGN KEY (`Clase_idClase`)
    REFERENCES `DonPreguntonBBDD`.`Clase` (`idClase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DonPreguntonBBDD`.`Profesores_has_Asignatuas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonPreguntonBBDD`.`Profesores_has_Asignatuas` (
  `Profesores_idProfesor` VARCHAR(20) NOT NULL,
  `Profesores_Clase_idClase` VARCHAR(20) NOT NULL,
  `Asignatuas_idAsignatura` VARCHAR(20) NOT NULL,
  `Asignatuas_Clase_idClase` VARCHAR(20) NOT NULL,
  `Clase_idClase` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Profesores_idProfesor`, `Profesores_Clase_idClase`, `Asignatuas_idAsignatura`, `Asignatuas_Clase_idClase`, `Clase_idClase`),
  INDEX `fk_Profesores_has_Asignatuas_Asignatuas1_idx` (`Asignatuas_idAsignatura` ASC, `Asignatuas_Clase_idClase` ASC),
  INDEX `fk_Profesores_has_Asignatuas_Profesores1_idx` (`Profesores_idProfesor` ASC, `Profesores_Clase_idClase` ASC),
  INDEX `fk_Profesores_has_Asignatuas_Clase1_idx` (`Clase_idClase` ASC),
  CONSTRAINT `fk_Profesores_has_Asignatuas_Profesores1`
    FOREIGN KEY (`Profesores_idProfesor` , `Profesores_Clase_idClase`)
    REFERENCES `DonPreguntonBBDD`.`Profesor` (`idProfesor` , `Clase_idClase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesores_has_Asignatuas_Asignatuas1`
    FOREIGN KEY (`Asignatuas_idAsignatura` , `Asignatuas_Clase_idClase`)
    REFERENCES `DonPreguntonBBDD`.`Asignatura` (`idAsignatura` , `Clase_idClase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesores_has_Asignatuas_Clase1`
    FOREIGN KEY (`Clase_idClase`)
    REFERENCES `DonPreguntonBBDD`.`Clase` (`idClase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DonPreguntonBBDD`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DonPreguntonBBDD`.`Horario` (
  `idHorario` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` VARCHAR(20) NOT NULL,
  `Clase_idClase` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idHorario`),
  INDEX `fk_Horario_Clase1_idx` (`Clase_idClase` ASC),
  CONSTRAINT `fk_Horario_Clase1`
    FOREIGN KEY (`Clase_idClase`)
    REFERENCES `DonPreguntonBBDD`.`Clase` (`idClase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

